version: '3.1'
services:
  oauth-server:
    image: mojdigitalstudio/nomis-oauth2-server:latest
    networks:
      - hmpps
    container_name: oauth-server
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  elite2-api:
    image: mojdigitalstudio/elite2-api:latest
    container_name: elite2-api
    depends_on:
    - oauth-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb
      
  sentence-planning-db:
    image: postgres
    networks:
    - hmpps
    container_name: sentence-planning-db
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=sentence-planning
    - POSTGRES_USER=sentence-planning
    - POSTGRES_DB=sentence-planning

  sentence-planning:
    build: .
    networks:
    - hmpps
    depends_on:
    - sentence-planning-db
    - oauth-server
    ports:
    - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    environment:
    - PORT=3000
    - DB_USER=sentence-planning
    - DB_PASS=sentence-planning
    - DB_SERVER=sentence-planning-db
    - DB_NAME=sentence-planning
    - DB_SSL_ENABLED=no
    - NOMIS_AUTH_URL=http://oauth-server:8080/auth
    - NOMIS_AUTH_EXTERNAL_URL=http://localhost:9090/auth


networks:
  hmpps:
