apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "sentence-planning.fullname" . }}
  labels:
    app: {{ template "sentence-planning.name" . }}
    chart: {{ template "sentence-planning.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "sentence-planning.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sentence-planning.name" . }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "sentence-planning.name" . }}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: gatekeeper
          image: "{{ .Values.gatekeeper.image.repository }}:{{ .Values.gatekeeper.image.tag }}"
          imagePullPolicy: "{{ .Values.gatekeeper.image.pullPolicy }}"
          ports:
            - name: gatekeeper
              containerPort: {{ .Values.gatekeeper.image.port }}
{{ include "gatekeeper.args" . | nindent 10 }}

        - name: sentence-planning
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 20
            timeoutSeconds: 5
{{ include "sentence-planning.envs" . | nindent 10 }}

