apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sentence-planning.fullname" . }}
type: Opaque
data:
  API_CLIENT_ID: {{ .Values.secrets.API_CLIENT_ID | b64enc | quote }}
  API_CLIENT_SECRET: {{ .Values.secrets.API_CLIENT_SECRET | b64enc | quote }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
