apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sentence-planning.fullname" . }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
