# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
minReadySeconds: 10
maxSurge: 100%
maxUnavailable: 50%

image:
  repository: docker.io/mojdigitalstudio/sentence-planning
  tag: latest
  pullPolicy: Always

gatekeeper:
  image:
    repository: mojdigitalstudio/oasys-keycloak-gatekeeper
    tag: latest
    pullPolicy: Always
    port: 8081

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "217.33.148.210/32,81.134.202.29/32,52.56.175.16/32,35.177.252.195/32,3.8.51.207/32,35.178.209.113/32,35.177.252.54/32"
  host: sentence-planning.service.justice.gov.uk
  path: /
  cert_secret: sentence-planning-cert

env:
  NOMIS_AUTH_URL: https://gateway.prod.nomis-api.service.hmpps.dsd.io/auth
  NOMIS_OAUTH_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwSkdtYWp6SW9POVdSY2owM2VTbQpFeWJTYnNJaEdkNkRWVDRxUWFSRTZwN3RIN1ppSklvRWtzczRkOFphMGhuYWJwa0JqWTYwS3NnMW5teXpoZVlSCithWXVtc0gxbm1JcmJ4ZCtqV043T3A2V1pteWRBU3JMek1XWVdBYlNHOHBXMXkxY1RwdkRaMTlBSGJTYTRRL2UKSnRlcDFscCsyMnVHMW5kTVRwclRkNjRLTkcyZnRwcmV3aFExeE5xdmtUWjZoQnVRRVJKMzFhUXBkRThNQTFxSwpDWnI3VDJxTk1BTWNkTlpia0FqRjVLOXE0alZ0QkY3WXFPeXJ0T1JmTldqYUJoWHA5TlN0YWJCTXBURTdQNm8vClhJaU9rcmltNjlzaG1OdDhVRlU3WUlJN0ZvejgzM29HZnk2dmtDRjRxcGpIZ0RNc21STjc1UXRrRmRtaU8xaDgKcHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  ELITE2_API_URL: https://gateway.nomis-api.service.hmpps.dsd.io/elite2api
  OASYSAPI_ENDPOINT_URL: https://dev.devtest.assessment-api.hmpps.dsd.io
  SENTENCEPLANNING_API_URL: http://sentence-planning-api.sentence-planning-prod.svc.cluster.local
  KEYCLOAK_REALM: https://oasys-auth.service.justice.gov.uk/auth/realms/sentence-planning-prod
  KEYCLOAK_UPSTREAM_URL: http://127.0.0.1:3000
  KEYCLOAK_REDIRECTION_URL: https://www.sentence-planning.service.justice.gov.uk
  
