# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
minReadySeconds: 10
maxSurge: 100%
maxUnavailable: 50%

image:
  repository: quay.io/hmpps/sentence-planning
  tag: latest
  pullPolicy: Always

gatekeeper:
  image:
    repository: mojdigitalstudio/oasys-keycloak-gatekeeper
    tag: latest
    pullPolicy: Always
    port: 8081

ingress:
  enabled: true
  enable_whitelist: true
  host: preprod.sentence-planning.service.justice.gov.uk
  path: /
  cert_secret: sentence-planning-cert

env:
  SENTENCEPLANNING_API_URL: http://sentence-planning-api.sentence-planning-preprod.svc.cluster.local
  KEYCLOAK_REALM: https://oasys-auth.service.justice.gov.uk/auth/realms/sentence-planning-preprod
  KEYCLOAK_UPSTREAM_URL: http://127.0.0.1:3000
  KEYCLOAK_REDIRECTION_URL: https://preprod.sentence-planning.service.justice.gov.uk

whitelist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  quantum: "62.25.109.197/32"
  quantum_alt: "212.137.36.230/32"
  digitalprisons1: "52.56.112.98/32"
  digitalprisons2: "52.56.118.154/32"
  j5-phones-1: "35.177.125.252/32"
  j5-phones-2: "35.177.137.160/32"
  dxc-mitcheldean: "195.92.38.16/28"
  ark-dom1-ttp1: "195.59.75.0/24"
  ark-dom1-farnborough: "194.33.192.0/24"
  ark-dom1-farnborough-psn: "51.247.3.0/24"
  ark-dom1-corsham: "194.33.196.0/24"
  ark-dom1-corsham-psn: "51.247.4.0/24"
  ark-dom1-non-live-1: "194.33.193.0/25"
  ark-dom1-non-live-2: "194.33.197.0/25"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
