# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
minReadySeconds: 10
maxSurge: 100%
maxUnavailable: 50%

image:
  repository: docker.io/mojdigitalstudio/sentence-planning
  tag: latest
  pullPolicy: Always

gatekeeper:
  image:
    repository: mojdigitalstudio/oasys-keycloak-gatekeeper
    tag: latest
    pullPolicy: Always
    port: 8081

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "217.33.148.210/32,81.134.202.29/32"
  host: development.sentence-planning.service.justice.gov.uk
  path: /

env:
  NOMIS_AUTH_URL: https://gateway.t3.nomis-api.hmpps.dsd.io/auth
  NOMIS_OAUTH_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBemN4N1lidzJCQVd2N1NzRUlVR1ANCml5SlNJRGd0cUJ4MTlUd203dUkzVFg1elJjclpsVXhjRW1QSkdVZ3krRDJKSWhWbHFtZXF3R1YyQ05PcVpCZ0cNCmo4ZUpHQTU5aUlUemU4ZG1SSk5JYzdsNmxESmc5RE5KVk9pTHFVbFpGRENJcXplSTYzb3E2dWhjY2c1RFBpVE4NCnFPR1pjOHVwTit3NWRack52KzJHTGd4SzJwZXRNVS9CaFllV2YzS3ZZSU8xNnYxdXZuRk9HTzEzSG9XdTVCdGQNClN0L1RnY2xGaFZMRWRHdzdYYmlZSG5OWklkaHdhTlFpWWdtWG1qWlZkTXlDUERNbzEwTGtWMXAzVXkxNXBNTXgNClVwc2xKYU8wNlZIYXJtY3ZWYzNleHg5NlpHTjE2T2U4ZWZoeG5Rdmhzd0ZrbXlYT25sSForNDI1MnJHcHlKTG8NCmx3SURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=
  ELITE2_API_URL: https://gateway.t3.nomis-api.hmpps.dsd.io/elite2api
  OASYSAPI_ENDPOINT_URL: https://dev.devtest.assessment-api.hmpps.dsd.io
  SENTENCEPLANNING_API_URL: http://sentence-planning-api.sentence-planning-development.svc.cluster.local
  KEYCLOAK_REALM: https://sentence-planning-keycloak-development.apps.live-1.cloud-platform.service.justice.gov.uk/auth/realms/sentence-planning
  KEYCLOAK_UPSTREAM_URL: http://127.0.0.1:3000
  KEYCLOAK_REDIRECTION_URL: https://development.sentence-planning.service.justice.gov.uk
  
