# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4
minReadySeconds: 10
maxSurge: 100%
maxUnavailable: 50%

image:
  repository: docker.io/mojdigitalstudio/sentence-planning
  tag: latest
  pullPolicy: Always

proxy:
  image:
    repository: quay.io/ukhomeofficedigital/nginx-proxy-govuk
    tag: latest
    pullPolicy: Always
    port: 10080

gatekeeper:
  image:
    repository: mojdigitalstudio/oasys-keycloak-gatekeeper
    tag: latest
    pullPolicy: Always
    port: 8081

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "217.33.148.210/32,81.134.202.29/32"
  host: sentence-planning-preprod.service.justice.gov.uk
  path: /
  
env:
  NOMIS_AUTH_URL: https://gateway.preprod.nomis-api.service.hmpps.dsd.io/auth
  NOMIS_OAUTH_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFqVGR1dEtLZVBSQmVBY2tnUzZwLwpsVitkNVlxYjNxMTh6NlV3aDFNTll4cDNIcVlwWVYrOTJ5RnhlMlE1UjdLVmpJeUt5MmZHQWpzV3krZVNOMjNUCkZURVVUeXdHdnc0SkJrRGRoaUUvKy80SjR2TWFHMzBYN29GdE9JUWIwaENFQVlWM3o4emc1WVd2OGZlRkVnWGcKSndKNUJzaStTQ29qM0hkOURFeTVkZlpNOWMvcGg5c3lhaktTVmJBbytEK1dqeFBYdThSd1FKT0FTSDQ1RXByVAozSTMvTXZZcmNWb3ZDeFFWclFjcGMzYmNFNGx6WHRZUlcvcElqR1FaQSsvVmIzV2V2bkdRYmJ3UzR6enl5M2s4CkRCZ0pzQVJlVDI1eHp0ckptRGlZZXBHYkVKVHV0alRqR2NVOG1qUjRWZ3gwdHdqMk9DMzBES3dXbGlrMzhXTWwKTlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
  ELITE2_API_URL: https://gateway.preprod.nomis-api.service.hmpps.dsd.io/elite2api
  OASYSAPI_ENDPOINT_URL: https://dev.devtest.assessment-api.hmpps.dsd.io
  SENTENCEPLANNING_API_URL: http://sentence-planning-api.sentence-planning-preprod.svc.cluster.local/
  KEYCLOAK_REALM: https://sentence-planning-keycloak-preprod.apps.live-1.cloud-platform.service.justice.gov.uk/auth/realms/sentence-planning
  KEYCLOAK_UPSTREAM_URL: http://127.0.0.1:3000
  KEYCLOAK_REDIRECTION_URL: https://sentence-planning-preprod.service.justice.gov.uk
  
