module.exports = Object.freeze({
  COMMENT_TYPES: {
    YOUR_RESPONSIVITY: 'YOUR_RESPONSIVITY',
    YOUR_SUMMARY: 'YOUR_SUMMARY',
    THEIR_RESPONSIVITY: 'THEIR_RESPONSIVITY',
    THEIR_SUMMARY: 'THEIR_SUMMARY',
  },
  ACTION_STATUS_TYPES: {
    NOT_STARTED: 'NOT_STARTED',
    IN_PROGRESS: 'IN_PROGRESS',
    PAUSED: 'PAUSED',
    COMPLETED: 'COMPLETED',
    PARTIALLY_COMPLETED: 'PARTIALLY_COMPLETED',
    ABANDONED: 'ABANDONED',
  },
  ACTION_RESPONSIBLE_TYPES: {
    SERVICE_USER: 'SERVICE_USER',
    PRACTITIONER: 'PRACTITIONER',
    OTHER: 'OTHER',
  },
})
